#!/bin/bash

: ${NUMA_NODE:=1}
: ${NUMA_WIDTH:=16}

LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
# GLOBAL_RANK=$OMPI_COMM_WORLD_RANK - IF THIS THEN PROFILE?
LOCAL_SIZE=$OMPI_COMM_WORLD_LOCAL_SIZE

## SIMPLEST SOLUTION TO ENSURE NO COLLISIONS
## JUST START AT THE BEGINNING.
if [[ $LOCAL_SIZE -gt $NUMA_WIDTH ]]; then NUMA_NODE=0; fi

## NEXT LEVEL OF COMPLEXITY.
## PUT THE FIRST RANKS ON THE TARGET NUMA UNTIL FULL.
## THEN PUT THE OTHER RANKS ON THE ALL THE OTHER NUMAS
## STARTING WITH 0. IF THE RANKS WOULD GO ON THE TARGET NUMA, 
## PUT THEM ON THE LAST NUMA.

## LOCAL RANK BECOMES PER NUMA RANK.
# if [[ $LOCAL_RANK -ge $NUMA_WIDTH ]]; then
#     NUMA_NODE_NEW=$(( (LOCAL_RANK-NUMA_WIDTH)/NUMA_WIDTH ))
#     LOCAL_RANK=$(( LOCAL_RANK%NUMA_WIDTH ))
#     if [[ $NUMA_NODE_NEW == $NUMA_NODE ]]; then
#         NUMA_NODE=$(( NNUMAS-1 ))
#     else
#         NUMA_NODE=$NUMA_NODE_NEW
#     fi
# fi

NUMA_START=$(( NUMA_WIDTH*NUMA_NODE ))
CORE=$(( LOCAL_RANK+NUMA_START ))

numactl --physcpubind=${CORE} --membind=${NUMA_NODE} "$@"